apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::511849100024:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-25T11:26:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1494"
  uid: fe322a49-0cb3-4e51-a21a-f13caef18eff
